# Generated by Django 4.2.28 on 2026-02-26 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_restaurant_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'rubric_categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RubricSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_score', models.PositiveIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.rubriccategory')),
            ],
            options={
                'db_table': 'rubric_subcategories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='credibility_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall 0-100 score', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='last_audit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='score_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.rubriccategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.restaurant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence',
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_category_applicable', models.BooleanField(default=True)),
                ('scored_timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.rubriccategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.restaurant')),
                ('scored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_given', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.rubricsubcategory')),
            ],
            options={
                'db_table': 'scores',
                'ordering': ['category', 'subcategory'],
                'unique_together': {('restaurant', 'subcategory')},
            },
        ),
    ]
