# Generated by Django 4.2.29 on 2026-03-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_auditevidencetimestamp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditevidence',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='auditevidence',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auditevidence',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='auditevidencetimestamp',
            name='audit_evidence',
        ),
        migrations.RemoveField(
            model_name='audithashchain',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='auditmerklenode',
            name='audit_evidence',
        ),
        migrations.RemoveField(
            model_name='auditmerklenode',
            name='left_child',
        ),
        migrations.RemoveField(
            model_name='auditmerklenode',
            name='right_child',
        ),
        migrations.RemoveField(
            model_name='auditmerklenode',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='auditmerkletree',
            name='audit',
        ),
        migrations.AlterUniqueTogether(
            name='auditscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='auditscore',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='auditscore',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auditscore',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='auditscore',
            name='scored_by',
        ),
        migrations.RemoveField(
            model_name='auditscore',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='audittamperdetection',
            name='audit_evidence',
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='AuditEvidence',
        ),
        migrations.DeleteModel(
            name='AuditEvidenceTimestamp',
        ),
        migrations.DeleteModel(
            name='AuditHashChain',
        ),
        migrations.DeleteModel(
            name='AuditMerkleNode',
        ),
        migrations.DeleteModel(
            name='AuditMerkleTree',
        ),
        migrations.DeleteModel(
            name='AuditScore',
        ),
        migrations.DeleteModel(
            name='AuditTamperDetection',
        ),
    ]
